"""initial schema

Revision ID: 24a6f9dbd994
Revises: 
Create Date: 2026-08-04 00:29:34.846365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a6f9dbd994'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('anomaly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger_type', sa.Enum('volume_spike', 'price_move', 'news', name='triggertype'), nullable=False),
    sa.Column('raw_metrics', sa.JSON(), nullable=False),
    sa.Column('watchdog_rationale', sa.String(), nullable=False),
    sa.Column('triggered_analyst_run', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('day_change_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'complete', 'failed', name='runstatus'), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anomaly_id')
    )
    op.create_table('brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thesis', sa.Enum('bullish', 'bearish', 'neutral', name='thesis'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('diff_from_prior', sa.String(), nullable=True),
    sa.Column('suggested_action', sa.Enum('buy', 'sell', 'hold', name='suggestedaction'), nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_run.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # agent_run.brief_id -> brief.id is a circular FK (brief.agent_run_id already
    # points the other way and is created above). use_alter=True on the ORM column
    # means autogenerate excludes it from the inline create_table('agent_run', ...)
    # on dialects that honor use_alter (e.g. Postgres), so it must be added
    # explicitly here now that both tables exist. batch_alter_table is required
    # because SQLite has no ALTER TABLE ADD CONSTRAINT support (it recreates the
    # table under the hood); on Postgres this compiles to a plain ALTER TABLE.
    with op.batch_alter_table('agent_run') as batch_op:
        batch_op.create_foreign_key(
            'fk_agent_run_brief_id', 'brief', ['brief_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Must drop the circular FK before dropping either table it touches — in
    # particular before dropping 'brief', which it references. batch mode is
    # required for SQLite (see upgrade()); harmless plain ALTER on Postgres.
    with op.batch_alter_table('agent_run') as batch_op:
        batch_op.drop_constraint('fk_agent_run_brief_id', type_='foreignkey')
    op.drop_table('brief')
    op.drop_table('agent_run')
    op.drop_table('price_snapshot')
    op.drop_table('anomaly')
    op.drop_table('ticker')
    # ### end Alembic commands ###
